FROM python:3.6-alpine

COPY requirements.txt /app/requirements.txt
COPY dev-requirements.txt /app/dev-requirements.txt
WORKDIR /app

# Install dependencies
# GCC and libffi-dev are required for pynacl
RUN apk --update add make gcc libffi-dev
RUN apk --update add --virtual build-dependencies python-dev build-base && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install -r dev-requirements.txt && \
    apk del build-dependencies

# Run the app
COPY . /app
CMD ["gunicorn", "-w", "2", "-b", ":5000", "--reload", "app:app"]
