FROM python:3.6-stretch

COPY requirements.txt /app/requirements.txt
COPY dev-requirements.txt /app/dev-requirements.txt
WORKDIR /app

# Install apt dependencies
# GCC and libffi-dev are required for pynacl
RUN apt-get update -y && \
    apt-get install -y libleveldb-dev

# Install pip dependencies
RUN pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install -r dev-requirements.txt

# Run the app
COPY . /app
CMD ["gunicorn", "-w", "2", "-b", ":5000", "--reload", "app:app"]
